#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopOnline_v2.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EShopOnlines")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCardVGA(CardVGA instance);
    partial void UpdateCardVGA(CardVGA instance);
    partial void DeleteCardVGA(CardVGA instance);
    partial void InsertRAM(RAM instance);
    partial void UpdateRAM(RAM instance);
    partial void DeleteRAM(RAM instance);
    partial void InsertCPU(CPU instance);
    partial void UpdateCPU(CPU instance);
    partial void DeleteCPU(CPU instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertManHinh(ManHinh instance);
    partial void UpdateManHinh(ManHinh instance);
    partial void DeleteManHinh(ManHinh instance);
    partial void InsertMayTinh(MayTinh instance);
    partial void UpdateMayTinh(MayTinh instance);
    partial void DeleteMayTinh(MayTinh instance);
    partial void InsertOCung(OCung instance);
    partial void UpdateOCung(OCung instance);
    partial void DeleteOCung(OCung instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EShopOnlinesConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CardVGA> CardVGAs
		{
			get
			{
				return this.GetTable<CardVGA>();
			}
		}
		
		public System.Data.Linq.Table<RAM> RAMs
		{
			get
			{
				return this.GetTable<RAM>();
			}
		}
		
		public System.Data.Linq.Table<CPU> CPUs
		{
			get
			{
				return this.GetTable<CPU>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<ManHinh> ManHinhs
		{
			get
			{
				return this.GetTable<ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<MayTinh> MayTinhs
		{
			get
			{
				return this.GetTable<MayTinh>();
			}
		}
		
		public System.Data.Linq.Table<OCung> OCungs
		{
			get
			{
				return this.GetTable<OCung>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CardVGA")]
	public partial class CardVGA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Model;
		
		private string _GPU;
		
		private string _ChuanGiaoTiep;
		
		private string _BoNhoVGA;
		
		private string _BangThong;
		
		private string _XungNhip;
		
		private string _CongGiaoTiep;
		
		private System.Nullable<int> _SoLuong;
		
		private string _XuatXu;
		
		private string _NamSX;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<MayTinh> _MayTinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnGPUChanging(string value);
    partial void OnGPUChanged();
    partial void OnChuanGiaoTiepChanging(string value);
    partial void OnChuanGiaoTiepChanged();
    partial void OnBoNhoVGAChanging(string value);
    partial void OnBoNhoVGAChanged();
    partial void OnBangThongChanging(string value);
    partial void OnBangThongChanged();
    partial void OnXungNhipChanging(string value);
    partial void OnXungNhipChanged();
    partial void OnCongGiaoTiepChanging(string value);
    partial void OnCongGiaoTiepChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public CardVGA()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._MayTinhs = new EntitySet<MayTinh>(new Action<MayTinh>(this.attach_MayTinhs), new Action<MayTinh>(this.detach_MayTinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(150)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPU", DbType="NVarChar(150)")]
		public string GPU
		{
			get
			{
				return this._GPU;
			}
			set
			{
				if ((this._GPU != value))
				{
					this.OnGPUChanging(value);
					this.SendPropertyChanging();
					this._GPU = value;
					this.SendPropertyChanged("GPU");
					this.OnGPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuanGiaoTiep", DbType="NVarChar(150)")]
		public string ChuanGiaoTiep
		{
			get
			{
				return this._ChuanGiaoTiep;
			}
			set
			{
				if ((this._ChuanGiaoTiep != value))
				{
					this.OnChuanGiaoTiepChanging(value);
					this.SendPropertyChanging();
					this._ChuanGiaoTiep = value;
					this.SendPropertyChanged("ChuanGiaoTiep");
					this.OnChuanGiaoTiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoNhoVGA", DbType="NVarChar(150)")]
		public string BoNhoVGA
		{
			get
			{
				return this._BoNhoVGA;
			}
			set
			{
				if ((this._BoNhoVGA != value))
				{
					this.OnBoNhoVGAChanging(value);
					this.SendPropertyChanging();
					this._BoNhoVGA = value;
					this.SendPropertyChanged("BoNhoVGA");
					this.OnBoNhoVGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BangThong", DbType="NVarChar(50)")]
		public string BangThong
		{
			get
			{
				return this._BangThong;
			}
			set
			{
				if ((this._BangThong != value))
				{
					this.OnBangThongChanging(value);
					this.SendPropertyChanging();
					this._BangThong = value;
					this.SendPropertyChanged("BangThong");
					this.OnBangThongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XungNhip", DbType="NVarChar(50)")]
		public string XungNhip
		{
			get
			{
				return this._XungNhip;
			}
			set
			{
				if ((this._XungNhip != value))
				{
					this.OnXungNhipChanging(value);
					this.SendPropertyChanging();
					this._XungNhip = value;
					this.SendPropertyChanged("XungNhip");
					this.OnXungNhipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongGiaoTiep", DbType="NVarChar(150)")]
		public string CongGiaoTiep
		{
			get
			{
				return this._CongGiaoTiep;
			}
			set
			{
				if ((this._CongGiaoTiep != value))
				{
					this.OnCongGiaoTiepChanging(value);
					this.SendPropertyChanging();
					this._CongGiaoTiep = value;
					this.SendPropertyChanged("CongGiaoTiep");
					this.OnCongGiaoTiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(100)")]
		public string XuatXu
		{
			get
			{
				return this._XuatXu;
			}
			set
			{
				if ((this._XuatXu != value))
				{
					this.OnXuatXuChanging(value);
					this.SendPropertyChanging();
					this._XuatXu = value;
					this.SendPropertyChanged("XuatXu");
					this.OnXuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(20)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CardVGA_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDCardVGA")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CardVGA_MayTinh", Storage="_MayTinhs", ThisKey="ID", OtherKey="CardVGA")]
		public EntitySet<MayTinh> MayTinhs
		{
			get
			{
				return this._MayTinhs;
			}
			set
			{
				this._MayTinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.CardVGA = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.CardVGA = null;
		}
		
		private void attach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.CardVGA1 = this;
		}
		
		private void detach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.CardVGA1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RAM")]
	public partial class RAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Loai;
		
		private string _DungLuong;
		
		private System.Nullable<bool> _TanNhiet;
		
		private string _CongNghe;
		
		private string _XuatXu;
		
		private string _NamSX;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<MayTinh> _MayTinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnDungLuongChanging(string value);
    partial void OnDungLuongChanged();
    partial void OnTanNhietChanging(System.Nullable<bool> value);
    partial void OnTanNhietChanged();
    partial void OnCongNgheChanging(string value);
    partial void OnCongNgheChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public RAM()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._MayTinhs = new EntitySet<MayTinh>(new Action<MayTinh>(this.attach_MayTinhs), new Action<MayTinh>(this.detach_MayTinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuong", DbType="NVarChar(150)")]
		public string DungLuong
		{
			get
			{
				return this._DungLuong;
			}
			set
			{
				if ((this._DungLuong != value))
				{
					this.OnDungLuongChanging(value);
					this.SendPropertyChanging();
					this._DungLuong = value;
					this.SendPropertyChanged("DungLuong");
					this.OnDungLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanNhiet", DbType="Bit")]
		public System.Nullable<bool> TanNhiet
		{
			get
			{
				return this._TanNhiet;
			}
			set
			{
				if ((this._TanNhiet != value))
				{
					this.OnTanNhietChanging(value);
					this.SendPropertyChanging();
					this._TanNhiet = value;
					this.SendPropertyChanged("TanNhiet");
					this.OnTanNhietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongNghe", DbType="NVarChar(100)")]
		public string CongNghe
		{
			get
			{
				return this._CongNghe;
			}
			set
			{
				if ((this._CongNghe != value))
				{
					this.OnCongNgheChanging(value);
					this.SendPropertyChanging();
					this._CongNghe = value;
					this.SendPropertyChanged("CongNghe");
					this.OnCongNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(150)")]
		public string XuatXu
		{
			get
			{
				return this._XuatXu;
			}
			set
			{
				if ((this._XuatXu != value))
				{
					this.OnXuatXuChanging(value);
					this.SendPropertyChanging();
					this._XuatXu = value;
					this.SendPropertyChanged("XuatXu");
					this.OnXuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(20)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDRAM")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_MayTinh", Storage="_MayTinhs", ThisKey="ID", OtherKey="RAM")]
		public EntitySet<MayTinh> MayTinhs
		{
			get
			{
				return this._MayTinhs;
			}
			set
			{
				this._MayTinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.RAM = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.RAM = null;
		}
		
		private void attach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.RAM1 = this;
		}
		
		private void detach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.RAM1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CPU")]
	public partial class CPU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Loai;
		
		private string _Socket;
		
		private string _TocDo;
		
		private string _IGP;
		
		private System.Nullable<int> _SoNhan;
		
		private string _BoNhoDem;
		
		private string _CongNghe;
		
		private string _CongSuat;
		
		private string _XuatXu;
		
		private string _NamSX;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<MayTinh> _MayTinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnSocketChanging(string value);
    partial void OnSocketChanged();
    partial void OnTocDoChanging(string value);
    partial void OnTocDoChanged();
    partial void OnIGPChanging(string value);
    partial void OnIGPChanged();
    partial void OnSoNhanChanging(System.Nullable<int> value);
    partial void OnSoNhanChanged();
    partial void OnBoNhoDemChanging(string value);
    partial void OnBoNhoDemChanged();
    partial void OnCongNgheChanging(string value);
    partial void OnCongNgheChanged();
    partial void OnCongSuatChanging(string value);
    partial void OnCongSuatChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public CPU()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._MayTinhs = new EntitySet<MayTinh>(new Action<MayTinh>(this.attach_MayTinhs), new Action<MayTinh>(this.detach_MayTinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socket", DbType="NVarChar(150)")]
		public string Socket
		{
			get
			{
				return this._Socket;
			}
			set
			{
				if ((this._Socket != value))
				{
					this.OnSocketChanging(value);
					this.SendPropertyChanging();
					this._Socket = value;
					this.SendPropertyChanged("Socket");
					this.OnSocketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDo", DbType="NVarChar(100)")]
		public string TocDo
		{
			get
			{
				return this._TocDo;
			}
			set
			{
				if ((this._TocDo != value))
				{
					this.OnTocDoChanging(value);
					this.SendPropertyChanging();
					this._TocDo = value;
					this.SendPropertyChanged("TocDo");
					this.OnTocDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGP", DbType="NVarChar(150)")]
		public string IGP
		{
			get
			{
				return this._IGP;
			}
			set
			{
				if ((this._IGP != value))
				{
					this.OnIGPChanging(value);
					this.SendPropertyChanging();
					this._IGP = value;
					this.SendPropertyChanged("IGP");
					this.OnIGPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhan", DbType="Int")]
		public System.Nullable<int> SoNhan
		{
			get
			{
				return this._SoNhan;
			}
			set
			{
				if ((this._SoNhan != value))
				{
					this.OnSoNhanChanging(value);
					this.SendPropertyChanging();
					this._SoNhan = value;
					this.SendPropertyChanged("SoNhan");
					this.OnSoNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoNhoDem", DbType="NVarChar(150)")]
		public string BoNhoDem
		{
			get
			{
				return this._BoNhoDem;
			}
			set
			{
				if ((this._BoNhoDem != value))
				{
					this.OnBoNhoDemChanging(value);
					this.SendPropertyChanging();
					this._BoNhoDem = value;
					this.SendPropertyChanged("BoNhoDem");
					this.OnBoNhoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongNghe", DbType="NVarChar(100)")]
		public string CongNghe
		{
			get
			{
				return this._CongNghe;
			}
			set
			{
				if ((this._CongNghe != value))
				{
					this.OnCongNgheChanging(value);
					this.SendPropertyChanging();
					this._CongNghe = value;
					this.SendPropertyChanged("CongNghe");
					this.OnCongNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongSuat", DbType="NVarChar(50)")]
		public string CongSuat
		{
			get
			{
				return this._CongSuat;
			}
			set
			{
				if ((this._CongSuat != value))
				{
					this.OnCongSuatChanging(value);
					this.SendPropertyChanging();
					this._CongSuat = value;
					this.SendPropertyChanged("CongSuat");
					this.OnCongSuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(150)")]
		public string XuatXu
		{
			get
			{
				return this._XuatXu;
			}
			set
			{
				if ((this._XuatXu != value))
				{
					this.OnXuatXuChanging(value);
					this.SendPropertyChanging();
					this._XuatXu = value;
					this.SendPropertyChanged("XuatXu");
					this.OnXuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(20)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDCPU")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_MayTinh", Storage="_MayTinhs", ThisKey="ID", OtherKey="CPU")]
		public EntitySet<MayTinh> MayTinhs
		{
			get
			{
				return this._MayTinhs;
			}
			set
			{
				this._MayTinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.CPU = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.CPU = null;
		}
		
		private void attach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.CPU1 = this;
		}
		
		private void detach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.CPU1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDTaiKhoan;
		
		private System.Nullable<int> _IDMayTinh;
		
		private System.Nullable<int> _IDRAM;
		
		private System.Nullable<int> _IDCPU;
		
		private System.Nullable<int> _IDCardVGA;
		
		private System.Nullable<int> _IDOCung;
		
		private System.Nullable<int> _IDManHinh;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private EntityRef<CardVGA> _CardVGA;
		
		private EntityRef<CPU> _CPU;
		
		private EntityRef<RAM> _RAM;
		
		private EntityRef<ManHinh> _ManHinh;
		
		private EntityRef<OCung> _OCung;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDTaiKhoanChanging(int value);
    partial void OnIDTaiKhoanChanged();
    partial void OnIDMayTinhChanging(System.Nullable<int> value);
    partial void OnIDMayTinhChanged();
    partial void OnIDRAMChanging(System.Nullable<int> value);
    partial void OnIDRAMChanged();
    partial void OnIDCPUChanging(System.Nullable<int> value);
    partial void OnIDCPUChanged();
    partial void OnIDCardVGAChanging(System.Nullable<int> value);
    partial void OnIDCardVGAChanged();
    partial void OnIDOCungChanging(System.Nullable<int> value);
    partial void OnIDOCungChanged();
    partial void OnIDManHinhChanging(System.Nullable<int> value);
    partial void OnIDManHinhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    #endregion
		
		public HoaDon()
		{
			this._CardVGA = default(EntityRef<CardVGA>);
			this._CPU = default(EntityRef<CPU>);
			this._RAM = default(EntityRef<RAM>);
			this._ManHinh = default(EntityRef<ManHinh>);
			this._OCung = default(EntityRef<OCung>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", DbType="Int NOT NULL")]
		public int IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMayTinh", DbType="Int")]
		public System.Nullable<int> IDMayTinh
		{
			get
			{
				return this._IDMayTinh;
			}
			set
			{
				if ((this._IDMayTinh != value))
				{
					this.OnIDMayTinhChanging(value);
					this.SendPropertyChanging();
					this._IDMayTinh = value;
					this.SendPropertyChanged("IDMayTinh");
					this.OnIDMayTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRAM", DbType="Int")]
		public System.Nullable<int> IDRAM
		{
			get
			{
				return this._IDRAM;
			}
			set
			{
				if ((this._IDRAM != value))
				{
					if (this._RAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDRAMChanging(value);
					this.SendPropertyChanging();
					this._IDRAM = value;
					this.SendPropertyChanged("IDRAM");
					this.OnIDRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCPU", DbType="Int")]
		public System.Nullable<int> IDCPU
		{
			get
			{
				return this._IDCPU;
			}
			set
			{
				if ((this._IDCPU != value))
				{
					if (this._CPU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCPUChanging(value);
					this.SendPropertyChanging();
					this._IDCPU = value;
					this.SendPropertyChanged("IDCPU");
					this.OnIDCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCardVGA", DbType="Int")]
		public System.Nullable<int> IDCardVGA
		{
			get
			{
				return this._IDCardVGA;
			}
			set
			{
				if ((this._IDCardVGA != value))
				{
					if (this._CardVGA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCardVGAChanging(value);
					this.SendPropertyChanging();
					this._IDCardVGA = value;
					this.SendPropertyChanged("IDCardVGA");
					this.OnIDCardVGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOCung", DbType="Int")]
		public System.Nullable<int> IDOCung
		{
			get
			{
				return this._IDOCung;
			}
			set
			{
				if ((this._IDOCung != value))
				{
					if (this._OCung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDOCungChanging(value);
					this.SendPropertyChanging();
					this._IDOCung = value;
					this.SendPropertyChanged("IDOCung");
					this.OnIDOCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDManHinh", DbType="Int")]
		public System.Nullable<int> IDManHinh
		{
			get
			{
				return this._IDManHinh;
			}
			set
			{
				if ((this._IDManHinh != value))
				{
					if (this._ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDManHinhChanging(value);
					this.SendPropertyChanging();
					this._IDManHinh = value;
					this.SendPropertyChanged("IDManHinh");
					this.OnIDManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CardVGA_HoaDon", Storage="_CardVGA", ThisKey="IDCardVGA", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public CardVGA CardVGA
		{
			get
			{
				return this._CardVGA.Entity;
			}
			set
			{
				CardVGA previousValue = this._CardVGA.Entity;
				if (((previousValue != value) 
							|| (this._CardVGA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CardVGA.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._CardVGA.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDCardVGA = value.ID;
					}
					else
					{
						this._IDCardVGA = default(Nullable<int>);
					}
					this.SendPropertyChanged("CardVGA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_HoaDon", Storage="_CPU", ThisKey="IDCPU", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public CPU CPU
		{
			get
			{
				return this._CPU.Entity;
			}
			set
			{
				CPU previousValue = this._CPU.Entity;
				if (((previousValue != value) 
							|| (this._CPU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CPU.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._CPU.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDCPU = value.ID;
					}
					else
					{
						this._IDCPU = default(Nullable<int>);
					}
					this.SendPropertyChanged("CPU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_HoaDon", Storage="_RAM", ThisKey="IDRAM", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public RAM RAM
		{
			get
			{
				return this._RAM.Entity;
			}
			set
			{
				RAM previousValue = this._RAM.Entity;
				if (((previousValue != value) 
							|| (this._RAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RAM.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._RAM.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDRAM = value.ID;
					}
					else
					{
						this._IDRAM = default(Nullable<int>);
					}
					this.SendPropertyChanged("RAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_HoaDon", Storage="_ManHinh", ThisKey="IDManHinh", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public ManHinh ManHinh
		{
			get
			{
				return this._ManHinh.Entity;
			}
			set
			{
				ManHinh previousValue = this._ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManHinh.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._ManHinh.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDManHinh = value.ID;
					}
					else
					{
						this._IDManHinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OCung_HoaDon", Storage="_OCung", ThisKey="IDOCung", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public OCung OCung
		{
			get
			{
				return this._OCung.Entity;
			}
			set
			{
				OCung previousValue = this._OCung.Entity;
				if (((previousValue != value) 
							|| (this._OCung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OCung.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._OCung.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDOCung = value.ID;
					}
					else
					{
						this._IDOCung = default(Nullable<int>);
					}
					this.SendPropertyChanged("OCung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_HoaDon", Storage="_TaiKhoan", ThisKey="IDTaiKhoan", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDTaiKhoan = value.ID;
					}
					else
					{
						this._IDTaiKhoan = default(int);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManHinh")]
	public partial class ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Loai;
		
		private string _KichThuoc;
		
		private string _DoPhanGiai;
		
		private string _XuatXu;
		
		private System.Nullable<int> _SoLuong;
		
		private string _NamSX;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnDoPhanGiaiChanging(string value);
    partial void OnDoPhanGiaiChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public ManHinh()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(150)")]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoPhanGiai", DbType="NVarChar(150)")]
		public string DoPhanGiai
		{
			get
			{
				return this._DoPhanGiai;
			}
			set
			{
				if ((this._DoPhanGiai != value))
				{
					this.OnDoPhanGiaiChanging(value);
					this.SendPropertyChanging();
					this._DoPhanGiai = value;
					this.SendPropertyChanged("DoPhanGiai");
					this.OnDoPhanGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(150)")]
		public string XuatXu
		{
			get
			{
				return this._XuatXu;
			}
			set
			{
				if ((this._XuatXu != value))
				{
					this.OnXuatXuChanging(value);
					this.SendPropertyChanging();
					this._XuatXu = value;
					this.SendPropertyChanged("XuatXu");
					this.OnXuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(20)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDManHinh")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MayTinh")]
	public partial class MayTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Loai;
		
		private System.Nullable<int> _CPU;
		
		private System.Nullable<int> _RAM;
		
		private System.Nullable<int> _OCung;
		
		private System.Nullable<int> _CardVGA;
		
		private string _HDH;
		
		private string _Chipset;
		
		private string _OQuang;
		
		private string _CongGiaoTiep;
		
		private string _LAN;
		
		private System.Nullable<int> _SoLuong;
		
		private string _NamSX;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntityRef<CardVGA> _CardVGA1;
		
		private EntityRef<CPU> _CPU1;
		
		private EntityRef<RAM> _RAM1;
		
		private EntityRef<OCung> _OCung1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnCPUChanging(System.Nullable<int> value);
    partial void OnCPUChanged();
    partial void OnRAMChanging(System.Nullable<int> value);
    partial void OnRAMChanged();
    partial void OnOCungChanging(System.Nullable<int> value);
    partial void OnOCungChanged();
    partial void OnCardVGAChanging(System.Nullable<int> value);
    partial void OnCardVGAChanged();
    partial void OnHDHChanging(string value);
    partial void OnHDHChanged();
    partial void OnChipsetChanging(string value);
    partial void OnChipsetChanged();
    partial void OnOQuangChanging(string value);
    partial void OnOQuangChanged();
    partial void OnCongGiaoTiepChanging(string value);
    partial void OnCongGiaoTiepChanged();
    partial void OnLANChanging(string value);
    partial void OnLANChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public MayTinh()
		{
			this._CardVGA1 = default(EntityRef<CardVGA>);
			this._CPU1 = default(EntityRef<CPU>);
			this._RAM1 = default(EntityRef<RAM>);
			this._OCung1 = default(EntityRef<OCung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="Int")]
		public System.Nullable<int> CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					if (this._CPU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCPUChanging(value);
					this.SendPropertyChanging();
					this._CPU = value;
					this.SendPropertyChanged("CPU");
					this.OnCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="Int")]
		public System.Nullable<int> RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					if (this._RAM1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCung", DbType="Int")]
		public System.Nullable<int> OCung
		{
			get
			{
				return this._OCung;
			}
			set
			{
				if ((this._OCung != value))
				{
					if (this._OCung1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOCungChanging(value);
					this.SendPropertyChanging();
					this._OCung = value;
					this.SendPropertyChanged("OCung");
					this.OnOCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardVGA", DbType="Int")]
		public System.Nullable<int> CardVGA
		{
			get
			{
				return this._CardVGA;
			}
			set
			{
				if ((this._CardVGA != value))
				{
					if (this._CardVGA1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCardVGAChanging(value);
					this.SendPropertyChanging();
					this._CardVGA = value;
					this.SendPropertyChanged("CardVGA");
					this.OnCardVGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDH", DbType="NVarChar(150)")]
		public string HDH
		{
			get
			{
				return this._HDH;
			}
			set
			{
				if ((this._HDH != value))
				{
					this.OnHDHChanging(value);
					this.SendPropertyChanging();
					this._HDH = value;
					this.SendPropertyChanged("HDH");
					this.OnHDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chipset", DbType="NVarChar(150)")]
		public string Chipset
		{
			get
			{
				return this._Chipset;
			}
			set
			{
				if ((this._Chipset != value))
				{
					this.OnChipsetChanging(value);
					this.SendPropertyChanging();
					this._Chipset = value;
					this.SendPropertyChanged("Chipset");
					this.OnChipsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OQuang", DbType="NVarChar(150)")]
		public string OQuang
		{
			get
			{
				return this._OQuang;
			}
			set
			{
				if ((this._OQuang != value))
				{
					this.OnOQuangChanging(value);
					this.SendPropertyChanging();
					this._OQuang = value;
					this.SendPropertyChanged("OQuang");
					this.OnOQuangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongGiaoTiep", DbType="NVarChar(150)")]
		public string CongGiaoTiep
		{
			get
			{
				return this._CongGiaoTiep;
			}
			set
			{
				if ((this._CongGiaoTiep != value))
				{
					this.OnCongGiaoTiepChanging(value);
					this.SendPropertyChanging();
					this._CongGiaoTiep = value;
					this.SendPropertyChanged("CongGiaoTiep");
					this.OnCongGiaoTiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAN", DbType="NVarChar(150)")]
		public string LAN
		{
			get
			{
				return this._LAN;
			}
			set
			{
				if ((this._LAN != value))
				{
					this.OnLANChanging(value);
					this.SendPropertyChanging();
					this._LAN = value;
					this.SendPropertyChanged("LAN");
					this.OnLANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(20)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CardVGA_MayTinh", Storage="_CardVGA1", ThisKey="CardVGA", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public CardVGA CardVGA1
		{
			get
			{
				return this._CardVGA1.Entity;
			}
			set
			{
				CardVGA previousValue = this._CardVGA1.Entity;
				if (((previousValue != value) 
							|| (this._CardVGA1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CardVGA1.Entity = null;
						previousValue.MayTinhs.Remove(this);
					}
					this._CardVGA1.Entity = value;
					if ((value != null))
					{
						value.MayTinhs.Add(this);
						this._CardVGA = value.ID;
					}
					else
					{
						this._CardVGA = default(Nullable<int>);
					}
					this.SendPropertyChanged("CardVGA1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CPU_MayTinh", Storage="_CPU1", ThisKey="CPU", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public CPU CPU1
		{
			get
			{
				return this._CPU1.Entity;
			}
			set
			{
				CPU previousValue = this._CPU1.Entity;
				if (((previousValue != value) 
							|| (this._CPU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CPU1.Entity = null;
						previousValue.MayTinhs.Remove(this);
					}
					this._CPU1.Entity = value;
					if ((value != null))
					{
						value.MayTinhs.Add(this);
						this._CPU = value.ID;
					}
					else
					{
						this._CPU = default(Nullable<int>);
					}
					this.SendPropertyChanged("CPU1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RAM_MayTinh", Storage="_RAM1", ThisKey="RAM", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public RAM RAM1
		{
			get
			{
				return this._RAM1.Entity;
			}
			set
			{
				RAM previousValue = this._RAM1.Entity;
				if (((previousValue != value) 
							|| (this._RAM1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RAM1.Entity = null;
						previousValue.MayTinhs.Remove(this);
					}
					this._RAM1.Entity = value;
					if ((value != null))
					{
						value.MayTinhs.Add(this);
						this._RAM = value.ID;
					}
					else
					{
						this._RAM = default(Nullable<int>);
					}
					this.SendPropertyChanged("RAM1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OCung_MayTinh", Storage="_OCung1", ThisKey="OCung", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public OCung OCung1
		{
			get
			{
				return this._OCung1.Entity;
			}
			set
			{
				OCung previousValue = this._OCung1.Entity;
				if (((previousValue != value) 
							|| (this._OCung1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OCung1.Entity = null;
						previousValue.MayTinhs.Remove(this);
					}
					this._OCung1.Entity = value;
					if ((value != null))
					{
						value.MayTinhs.Add(this);
						this._OCung = value.ID;
					}
					else
					{
						this._OCung = default(Nullable<int>);
					}
					this.SendPropertyChanged("OCung1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OCung")]
	public partial class OCung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _HangSX;
		
		private string _Loai;
		
		private string _TocDoVongQuay;
		
		private string _BoNhoDem;
		
		private string _ChuanKetNoi;
		
		private string _DungLuong;
		
		private string _KichThuoc;
		
		private string _XuatXu;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _GiamGia;
		
		private string _LinkImg1;
		
		private string _LinkImg2;
		
		private string _LinkImg3;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<MayTinh> _MayTinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnHangSXChanging(string value);
    partial void OnHangSXChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnTocDoVongQuayChanging(string value);
    partial void OnTocDoVongQuayChanged();
    partial void OnBoNhoDemChanging(string value);
    partial void OnBoNhoDemChanged();
    partial void OnChuanKetNoiChanging(string value);
    partial void OnChuanKetNoiChanged();
    partial void OnDungLuongChanging(string value);
    partial void OnDungLuongChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnXuatXuChanging(string value);
    partial void OnXuatXuChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnLinkImg1Changing(string value);
    partial void OnLinkImg1Changed();
    partial void OnLinkImg2Changing(string value);
    partial void OnLinkImg2Changed();
    partial void OnLinkImg3Changing(string value);
    partial void OnLinkImg3Changed();
    #endregion
		
		public OCung()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._MayTinhs = new EntitySet<MayTinh>(new Action<MayTinh>(this.attach_MayTinhs), new Action<MayTinh>(this.detach_MayTinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangSX", DbType="NVarChar(150)")]
		public string HangSX
		{
			get
			{
				return this._HangSX;
			}
			set
			{
				if ((this._HangSX != value))
				{
					this.OnHangSXChanging(value);
					this.SendPropertyChanging();
					this._HangSX = value;
					this.SendPropertyChanged("HangSX");
					this.OnHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(150)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDoVongQuay", DbType="NVarChar(100)")]
		public string TocDoVongQuay
		{
			get
			{
				return this._TocDoVongQuay;
			}
			set
			{
				if ((this._TocDoVongQuay != value))
				{
					this.OnTocDoVongQuayChanging(value);
					this.SendPropertyChanging();
					this._TocDoVongQuay = value;
					this.SendPropertyChanged("TocDoVongQuay");
					this.OnTocDoVongQuayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoNhoDem", DbType="NVarChar(100)")]
		public string BoNhoDem
		{
			get
			{
				return this._BoNhoDem;
			}
			set
			{
				if ((this._BoNhoDem != value))
				{
					this.OnBoNhoDemChanging(value);
					this.SendPropertyChanging();
					this._BoNhoDem = value;
					this.SendPropertyChanged("BoNhoDem");
					this.OnBoNhoDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuanKetNoi", DbType="NVarChar(100)")]
		public string ChuanKetNoi
		{
			get
			{
				return this._ChuanKetNoi;
			}
			set
			{
				if ((this._ChuanKetNoi != value))
				{
					this.OnChuanKetNoiChanging(value);
					this.SendPropertyChanging();
					this._ChuanKetNoi = value;
					this.SendPropertyChanged("ChuanKetNoi");
					this.OnChuanKetNoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuong", DbType="NVarChar(100)")]
		public string DungLuong
		{
			get
			{
				return this._DungLuong;
			}
			set
			{
				if ((this._DungLuong != value))
				{
					this.OnDungLuongChanging(value);
					this.SendPropertyChanging();
					this._DungLuong = value;
					this.SendPropertyChanged("DungLuong");
					this.OnDungLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(100)")]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatXu", DbType="NVarChar(150)")]
		public string XuatXu
		{
			get
			{
				return this._XuatXu;
			}
			set
			{
				if ((this._XuatXu != value))
				{
					this.OnXuatXuChanging(value);
					this.SendPropertyChanging();
					this._XuatXu = value;
					this.SendPropertyChanged("XuatXu");
					this.OnXuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg1", DbType="NVarChar(1000)")]
		public string LinkImg1
		{
			get
			{
				return this._LinkImg1;
			}
			set
			{
				if ((this._LinkImg1 != value))
				{
					this.OnLinkImg1Changing(value);
					this.SendPropertyChanging();
					this._LinkImg1 = value;
					this.SendPropertyChanged("LinkImg1");
					this.OnLinkImg1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg2", DbType="NVarChar(1000)")]
		public string LinkImg2
		{
			get
			{
				return this._LinkImg2;
			}
			set
			{
				if ((this._LinkImg2 != value))
				{
					this.OnLinkImg2Changing(value);
					this.SendPropertyChanging();
					this._LinkImg2 = value;
					this.SendPropertyChanged("LinkImg2");
					this.OnLinkImg2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkImg3", DbType="NVarChar(1000)")]
		public string LinkImg3
		{
			get
			{
				return this._LinkImg3;
			}
			set
			{
				if ((this._LinkImg3 != value))
				{
					this.OnLinkImg3Changing(value);
					this.SendPropertyChanging();
					this._LinkImg3 = value;
					this.SendPropertyChanged("LinkImg3");
					this.OnLinkImg3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OCung_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDOCung")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OCung_MayTinh", Storage="_MayTinhs", ThisKey="ID", OtherKey="OCung")]
		public EntitySet<MayTinh> MayTinhs
		{
			get
			{
				return this._MayTinhs;
			}
			set
			{
				this._MayTinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.OCung = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.OCung = null;
		}
		
		private void attach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.OCung1 = this;
		}
		
		private void detach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.OCung1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _SDT;
		
		private string _Email;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<bool> _Loai;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnLoaiChanging(System.Nullable<bool> value);
    partial void OnLoaiChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(150)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(150)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(150)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(150)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Bit")]
		public System.Nullable<bool> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_HoaDon", Storage="_HoaDons", ThisKey="ID", OtherKey="IDTaiKhoan")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
}
#pragma warning restore 1591
